### ISSUE TITLE
Download live streams in 1440p and mkv format

### ISSUE THREAD

**Issue by qwertyq11** [mrwnwttk/youtube_stream_capture#5]
Love the tool by the way! :D
These are more like questions than issues.

So the first question is, how do you make it so it downloads the streams in 1440p60 and not in 1080p because it always defaults to that. I want to always have the highest quality when downloading. Are there any parameters I'm missing or don't know?
This is how I use the tool to download a stream that is 1440p60
`Python youtube_stream_capture.py https://www.youtube.com/watch?v=h3EQcYNavMw`

Second and last questions: is there a way to make it use the .mkv format instead of .mp4 when merging the files into one?

**Comment by mrwnwttk** [comment]
If 1440p60 is only being streamed as a VP9 stream then it won't grab the stream. VP9 support is experimental and seems to break things 80% of the time. Audio gets out of sync, etc. I'll happily add proper support for it, but for now I've decided to comment it out (line 65 if you're curious). It also says so in the README.

>  is there a way to make it use the .mkv format instead of .mp4 when merging the files into one?

Yes. Just change the file extension of the intermediate and output files inside the merge script. If you decide to use VP9 then you'll have no choice but to change the container to MKV because MP4 doesn't support VP8/9 or OPUS.
