### ISSUE TITLE
Issues when downloading 

### ISSUE THREAD

**Issue by Ezendeis** [mrwnwttk/youtube_stream_capture#9]
Hi , I'm pretty new to this but I manage to download on my first try . But my second try doesn't seem to work well and I couldn't manage to make it work at all , Any idea how to fix this ? 

![image](https://user-images.githubusercontent.com/84282083/118403209-4a557a00-b665-11eb-85ae-ad267f16ec6d.png)

**Comment by Ezendeis** [comment]
I also got this problem 
![image](https://user-images.githubusercontent.com/84282083/118404563-580dfe00-b66b-11eb-9b6a-f3b82e02958c.png)

**Comment by mrwnwttk** [comment]
Response to #1: that's a member's only livestream. Dump your cookie and use it. All the info you need for that is in the README.

Response to #2: Looks like it's working just fine, did you properly install aria2c? Just tested it on a different livestream (because the one you tried it on has since ended) and everything worked as expected.

**Comment by Ezendeis** [comment]
Thanks for your reply I do have aria2c installed and I just tested again on another stream and it working fine....regarding to the second picture I actually enter the script too early.. like at the moment that the stream start I pressed it that's why It's stuck like that
